---
fixtures:
  repositories:
    simplib: "git://github.com/simp/pupmod-simp-simplib"
    stdlib:
      repo: "git://github.com/simp/puppetlabs-stdlib"
      branch: "simp-master"
  symlinks:
    simpcat: "#{source_dir}"
